### ISSUE TITLE
I have no idea what this package does

### ISSUE THREAD

**Issue by rugk** [paulpflug/opened-files#17]
Sorry, but I have no idea what this package does. I see no differences in the tree view and there is nowhere any list of files which are currently open.
BTW I also don't know what you mean with 'open' - opened in Atom (= currently edited) or opened by another program?

Please note that I also use a few other packages which modify the tree-view, so should this be the source why I see nothing changed, I'll have to narrow that down.

So maybe it would be good to adjust your Readme. (and explain it me... :confused:)

**Comment by bluenote10** [comment]
Well, I take it the package is supposed to show the files which are opened in Atom (= tabs).

However, I also have no idea where the "opened file list" is. It is not in the tree view (is this where it should be?) and I have no idea how to open the list in the first place.

**Comment by otjutt** [comment]
I installed this package to have a list of opened files (= current opened tabs) in the left pane. But I think that this package did nothing. I'm disappointed to see that such a simple thing is not present in atom editor which comes by default in sublime text editor.

**Comment by lostdj** [comment]
^ Same.

**Comment by paulpflug** [comment]
It "should" open a panel above the tree-view.. 
Accidentally I had all errors catched to the dev tools > console
So if something happened it just didn't open (and printed in console, but who is looking there anyways ;). This is fixed in 0.2.7, so I'm curious which errors you initially got...

**Comment by rugk** [comment]
> Accidentally I had all errors catched to the dev tools > console
> So if something happened it just didn't open (and printed in console, but who is looking there anyways ;). This is fixed in 0.2.7, so I'm curious which errors you initially got...

I've had installed 0.2.5 and just right now I tried to get some errors of this package and even in the dev console are none.

**Comment by rugk** [comment]
With v0.2.8 I still don't see any list of opened tabs.

**Comment by paulpflug** [comment]
should work with 0.3.1

**Comment by otjutt** [comment]
For me, switching to Visual Studio Code resolved this issue.

**Comment by paulpflug** [comment]
:+1:
