### ISSUE TITLE
opened files persistant across open windows

### ISSUE THREAD

**Issue by amebel** [paulpflug/opened-files#7]
I hope the pictures explains the issue
![screenshot from 2015-06-25 15 38 15](https://cloud.githubusercontent.com/assets/2135577/8349530/505f6f48-1b50-11e5-9ced-85af441c7a69.png)

**Comment by paulpflug** [comment]
solved in 0.2.1
opened files can be saved manually instead of auto saving

**Comment by amebel** [comment]
Thanks
