### ISSUE TITLE
opened file list persist after closing files

### ISSUE THREAD

**Issue by amebel** [paulpflug/opened-files#8]
Hope the picture below is enough. Maybe a setting options could be added for remembering the history of opened files.
![screenshot from 2015-06-25 15 42 30](https://cloud.githubusercontent.com/assets/2135577/8349608/d0fcbfde-1b50-11e5-81a7-c239d3247e35.png)

**Comment by amebel** [comment]
also on closing and opening the window the history persists

**Comment by paulpflug** [comment]
that was intended, but you got a point here I guess :smile:

I will add a button to save and remove autosave

**Comment by amebel** [comment]
thanks

**Comment by paulpflug** [comment]
should work in 0.2.1
I hope you like it

**Comment by paulpflug** [comment]
now I read it carefully :smile:

Not deleting the entries after close is intended. You can click the X or `ctrl+alt+w` to close all entries.
I want to work with the preview functionality of the tabs package, which is not possible yet.
The idea is, that a file goes in the opened files list only if it is no preview tab, but stays there for quick reference even after close.

**Comment by amebel** [comment]
:+1:  thanks

That is a good idea. Would be handy in case  you use previews with go-to-decleration and return-from-declaration (i use atom-ctags) multiple times in a session/task. In the picture most of the entries came about because of such activity.
